### PR TITLE
Make it work with 5.8

### PR DESCRIPTION
**Pull request by astj**
I'd like to use `Test::MockTime::HiRes` in `Plack`, but `Plack` supports 5.8. (refs: https://github.com/plack/Plack/pull/551 )
So I'd like to make `Test::MockTime::HiRes` in 5.8

### CODE REVIEW

**Comment by astj** [comment]
@tarao Please review this p-r :sob:

**Comment by tarao** [comment]
LGTM

**Comment by astj** [comment]
Thanks alot!

**Comment by miyagawa** [comment]
Please ship it to CPAN so we can use it in downstream.

**Comment by tarao** [comment]
Done: 9531d122272f487a5205d629ea204d116d15588d

**Pull request merged**
